"""
ui/ai_analysis.py
=================
Renders the "🤖 AI Analysis" tab.

Displays a data-readiness summary, a "Run AI Analysis" button, and
the formatted markdown report returned by the text model.

Also renders an expander with raw LLM output (for transparency / debugging)
and an AI configuration detail table.
"""

from datetime import datetime

import streamlit as st

from config import Settings
from core import analyze_spending
from data import get_price_df
from ui.styles import section_title


def render(settings: Settings) -> None:
    """Render the complete AI Analysis tab content.

    Args:
        settings: Application settings (model names, API key).
    """
    section_title("AI Budget Analysis & Inflation Report")

    analysis_df = get_price_df()
    api_configured = bool(settings.openrouter_api_key)

    # ── Guard: API key missing ────────────────────────────────────────────────
    if not api_configured:
        st.error(
            "🔑 **API Key Required:** Set `OPENROUTER_API_KEY` in your `.env` file "
            "to enable AI Analysis.",
            icon="🚨",
        )
        _render_config_expander(settings, api_configured)
        return

    # ── Guard: No data ────────────────────────────────────────────────────────
    if analysis_df.empty:
        st.info(
            "📭 No data to analyze yet. Log at least a few price entries in the "
            "**✏️ Log Prices** tab first.",
            icon="💡",
        )
        return

    # ── Data readiness summary ────────────────────────────────────────────────
    entry_count = len(analysis_df)
    unique_items = analysis_df["Item"].nunique()

    col_info, col_action = st.columns([3, 1])
    with col_info:
        st.markdown(
            f"""
            <div style="background:#1c2b3a;border:1px solid #2d4a6e;
                        border-radius:8px;padding:1rem 1.25rem;margin-bottom:1rem;">
                <p style="color:#8ab4d4;margin:0;font-size:0.85rem;font-weight:600;">
                    DATA READY FOR ANALYSIS
                </p>
                <p style="color:#e8f0fe;margin:0.3rem 0 0 0;font-size:1rem;">
                    📊 <strong>{entry_count}</strong> price entries across
                    <strong>{unique_items}</strong> unique items
                </p>
            </div>
            """,
            unsafe_allow_html=True,
        )

    with col_action:
        run_analysis = st.button(
            "🤖 Run AI Analysis",
            type="primary",
            use_container_width=True,
            key="run_analysis_btn",
        )

    # ── Trigger analysis ──────────────────────────────────────────────────────
    if run_analysis:
        with st.spinner("🧠 Analyzing your spending data with AI..."):
            try:
                analysis_result, raw_response = analyze_spending(analysis_df, settings)
                st.session_state["ai_analysis_result"] = analysis_result
                st.session_state["ai_raw_response"] = raw_response
            except (RuntimeError, ValueError) as exc:
                st.error(f"❌ Analysis failed: {exc}", icon="🚨")

    # ── Display cached results ────────────────────────────────────────────────
    if st.session_state.get("ai_analysis_result"):
        st.markdown("---")
        st.markdown("### 📋 Economist's Report")
        st.markdown(st.session_state["ai_analysis_result"])

        with st.expander(
            "🔍 View Raw AI Response (for debugging / transparency)", expanded=False
        ):
            st.code(st.session_state["ai_raw_response"], language="markdown")

        st.markdown("---")
        st.caption(
            f"Analysis generated by `{settings.text_model}` via OpenRouter · "
            f"{datetime.now().strftime('%Y-%m-%d %H:%M')}"
        )

    _render_config_expander(settings, api_configured)


def _render_config_expander(settings: Settings, api_configured: bool) -> None:
    """Render the AI configuration detail expander."""
    with st.expander("⚙️ AI Configuration Details", expanded=False):
        st.markdown(
            f"""
| Setting | Value |
|---------|-------|
| **Text Model** | `{settings.text_model}` |
| **Vision Model** | `{settings.vision_model}` |
| **API Base URL** | `{settings.openrouter_api_url}` |
| **API Key Source** | `.env` → `os.environ.get()` |
| **Key Configured** | {'✅ Yes' if api_configured else '❌ No — check .env file'} |
            """
        )
